#!/bin/bash
# Detect leaked secrets that are about to be committed.

if [ "$SKIPLEAKS" == true ]; then
  echo WARNING: skipping leaked secrets detection ...
  exit 0
fi

set -xe

# --redact prevents another leak path through 
# terminal scrollback or copied  logs
gitleaks protect --no-banner --staged --redact

