# Inserts a blank line between shell prompts
add_newline = false

format = """
$status\
$username\
$hostname\
$kubernetes\
$aws\
$env_var\
$sudo\
$container\
$shell\
$line_break\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$jobs\
$character"""

[status]
disabled = false
success_symbol = 'OK'
format = '[↳\[$symbol $status\]]($style) '
map_symbol = true
style = ''

[username]
style_user = 'yellow'
format = '[$user]($style)@'

[hostname]
style = 'green'
format = '[$ssh_symbol$hostname]($style) '

[kubernetes]
disabled = false
style = "fg:26"
format = '[$symbol$context( \($namespace\))]($style) '

[aws]
style = "bold blue"
format = '[$symbol($profile )(\[$duration\] )]($style)'

[line_break]
disabled = false

[directory]
style = "bold blue"
truncate_to_repo = true
use_logical_path = false
[directory.substitutions]
"/private/play" = "~/play"

[git_branch]
format = "[$branch(:$remote_branch)]($style) "
truncation_length = 25

[jobs]
symbol = "& "
number_threshold = 1

[character]
success_symbol = '\$'
error_symbol = '\$'