# Inserts a blank line between shell prompts
add_newline = false

format = """
$username\
$hostname\
$aws\
$gcloud\
$kubernetes\
$env_var\
$sudo\
$container\
$shell\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$jobs\
$character"""

[username]
style_user = 'yellow'
format = '[$user]($style)@'

[hostname]
style = 'green'
format = '[$ssh_symbol$hostname]($style) '

[aws]
disabled = false
style = "fg:202"
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[gcloud]
disabled = true
symbol = '☁️ '
format = '[$symbol(\($region\))]($style) '

[kubernetes]
disabled = false
style = "fg:25"
format = '[$symbol$context( \($namespace\))]($style) '

[line_break]
disabled = false

[directory]
style = 'bright-blue'
truncation_length   = 3
truncate_to_repo    = false
truncation_symbol   = '…/'
use_logical_path    = false
[directory.substitutions]
#"/private/play"     = "~/play"
#"/private/tmp"      = "/tmp"

[git_branch]
format = "[$branch(:$remote_branch)]($style) "
#truncation_length = 25

[jobs]
symbol = "& "
number_threshold = 1

[character]
success_symbol = '[\$]($style)'
error_symbol = '[\$](bold red)'
